config/routes.rb
Rails.application.routes.draw do
  resources :requests

  get 'statistics/basic'

  get 'sessions/new'

  resources :rate_user_tutorials

  resources :read_user_tutorials

  resources :keyword_tutorials

  resources :steps

  resources :categories

  resources :topics

  resources :keywords

  resources :users

  resources :tutorials
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  get    'mytutorials'  => 'tutorials#myindex'
  get    'statistics'  => 'statistics#basic'
  
  
  

  root 'categories#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  #Topic(id: integer, name: string, category_id: integer, created_at: datetime, updated_at: datetime) 
    validates :name, presence: true
    validates :category_id, presence: true
    belongs_to :category
    has_many :tutorials
    has_many :requests
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:new, :edit, :update, :destroy]
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :category_id)
    end
end
def check_admin
	if !logged_in? || current_user.user_name!='admin'
    redirect_to root_path, notice: "Sorry, you don't have privilege to change category."
  end

	end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
    <!-- Page Content -->
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>
      <ul>
        <% @topic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <!-- New Category Details Column -->
    <div class="col-md-4">
      <h4>Title</h4>      
      <%= f.text_field :name, class:'form-control' %> 
      &nbsp;

      <h4>Category List</h4>
      <%= f.collection_select :category_id, Category.all, :id, :name, {:include_blank => false},{:class => 'form-control'} %>
      &nbsp;
      <%= f.submit "Create Topic", class:'btn btn-lg btn-default btn-block'%>
    </div>
  </div>
<%end%>

app/views/topics/edit.html.erb
<!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Editing Topic
                    <small></small>
                </h1>
            </div>
        </div>
        <!-- /.row -->


 				<%= render 'form' %>
 				<div class="row">
                <div class="col-md-8">
                	<%= link_to 'Show', @topic, class:'btn btn-lg btn-default btn-block', style:'width:10%', type:'submit' %> 
					<%= link_to 'Back', topics_path, class:'btn btn-lg btn-default btn-block', style:'width:10%', type:'submit' %>

                 </div>


        </div>
        <!-- /.row -->

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
            <div class="col-lg-12">
              <h1 class="page-header">Listing Topics
                    
                </h1>
            </div>
        </div>

<!-- <%= url_for :controller => 'tutorials', :action => 'myindex' %> -->
 <div class="col-md-12"> 
<div class="well">
<table style="margin-left:30px">
  <thead>
    <tr>
      <th style="padding-right:20px"><h1 class="page-header"><small> Name</small></h1></th>
      <th style="padding-right:20px"><h1 class="page-header"><small> Category</small></h1></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td style="padding-right:20px;text-align:left"><%= link_to topic.name,topic %>(<%=topic.tutorials.count%> tutorials)</td>
        <td style="padding-right:20px; text-align:center"><%= link_to topic.category.name, topic.category %></td>
        
    <%if current_user && current_user.user_name=='admin'%>
        <td style="padding-right:20px"><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td style="padding-right:20px"><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
     <% end %>
  </tbody>
</table>

</div>

 

          <%if current_user && current_user.user_name=='admin'%>
              <%= link_to 'New Topics', new_topic_path, class:'btn btn-lg btn-default btn-block', type:'submit', width:'10%' %>
              <%end%>

app/views/topics/new.html.erb
<div class="row">
  <div class="col-lg-12">
  <h1 class="page-header">New Topic</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="col-md-4">
    <%= link_to 'Back', categories_path, class:'btn btn-lg btn-default btn-block', type:'submit' %>
  </div>
</div>

app/views/topics/show.html.erb
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">

                <h1 class="page-header">
                 <small><%= link_to 'Home', categories_path %> > <%= link_to @topic.category.name, @topic.category%> >  <%= @topic.name %>
				</small></br>    
                    <!-- <small>Name:</small> <small><%= @topic.name %></small>  -->
                    <small colspan="3"></small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">

                <div class="col-md-8">
                <!-- Tutorials List Well -->
                <div class="well">
                    <h4>List of Tutorials</h4>
                    <%@topic.tutorials.each do |tutorial|%>
                    <div class="row">
                        <div class="col-lg-12">
                            <ul class="list-unstyled">
                                <li><span><%=link_to tutorial.title, tutorial%></span><span>&nbsp;by</span><span><a href="#">&nbsp;<%=link_to tutorial.user.user_name, tutorial.user%></a></span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                    <%end%>
                </div>

            </div>


        </div>
        <!-- /.row -->