config/routes.rb
Rails.application.routes.draw do
  resources :requests

  get 'statistics/basic'

  get 'sessions/new'

  resources :rate_user_tutorials

  resources :read_user_tutorials

  resources :keyword_tutorials

  resources :steps

  resources :categories

  resources :topics

  resources :keywords

  resources :users

  resources :tutorials
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  get    'mytutorials'  => 'tutorials#myindex'
  get    'statistics'  => 'statistics#basic'
  
  
  

  root 'categories#index'

end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  
  # Tutorial(id: integer, title: string, tutorial_level: integer, user_id: integer, topic_id: integer, created_at: datetime, updated_at: datetime) 
    validates :user_id, presence: true
    validates :topic_id, presence: true
    validates :title, presence: true
    validates :tutorial_level, presence: true, :numericality => { :greater_than => 0, :less_than_or_equal_to => 5 }  
    belongs_to :user
    has_many :read_user_tutorials
    has_many :read_users, :through => :read_user_tutorials, source: "user"
    has_many :rate_user_tutorials
    has_many :rate_users, :through => :rate_user_tutorials, source: "user"
    has_many :keyword_tutorials
    has_many :keywords, :through => :keyword_tutorials
    has_many :steps
    belongs_to :topic
    accepts_nested_attributes_for :steps, :reject_if => :all_blank, :allow_destroy => true
    accepts_nested_attributes_for :keywords, :reject_if => :all_blank, :allow_destroy => true
    # searchable do
    #   text :title
    #   text :steps do
    #     steps.map{ |step| step.description}
    #   end
    # end
    
    
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show]
  before_action :set_tutorial_and_authenticate_user, only: [:edit, :update, :destroy]
  # GET /tutorials
  # GET /tutorials.json
  def index
    if params[:search]
      @tutorials=Tutorial.find_by_sql("SELECT T.*
      FROM tutorials T
      WHERE T.title LIKE '%" + params[:search] + "%'
      union
      SELECT T.*
      FROM tutorials T, steps S
      WHERE S.tutorial_id=T.id and 
      S.description LIKE '%" + params[:search] + "%'
      union
      SELECT T.*
      FROM tutorials T, keywords K,keyword_tutorials KT
      WHERE KT.tutorial_id=T.id and 
      KT.keyword_id=K.id and
      K.name LIKE '%" + params[:search] + "%'")
    else
      @tutorials = Tutorial.all
    end
  end
  
  def myindex
    if logged_in?
      @tutorials = current_user.tutorials
    else
      redirect_to tutorials_path
    end
  end
  
  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
    @avg_score=@tutorial.rate_user_tutorials.collect(&:score).sum.to_f/@tutorial.rate_user_tutorials.length if @tutorial.rate_user_tutorials.length > 0
    @relavent_tutorials=Tutorial.find_by_sql("SELECT distinct T.* 
    FROM tutorials T, keywords K, keyword_tutorials KT
    WHERE T.id!=" + @tutorial.id.to_s + " and
    T.id=KT.tutorial_id and 
    KT.keyword_id=K.id and
    K.name in
    (SELECT K.name
    FROM keywords K, keyword_tutorials KT
    WHERE K.id=KT.keyword_id and KT.tutorial_id=" + @tutorial.id.to_s + ") limit 10")
    if logged_in?
      if !@tutorial.read_users.include?(current_user)
        @tutorial.read_users<<current_user
      end
    end
  end

  # GET /tutorials/new
  def new
    if logged_in?
      @tutorial = Tutorial.new
    else
      redirect_to login_path
    end
  end

  # GET /tutorials/1/edit
  def edit
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    if !logged_in?
      redirect_to loggin_path
    end
    @tutorial = Tutorial.new(tutorial_params)
    @tutorial.user=current_user
    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully created.' }
        format.json { render :show, status: :created, location: @tutorial }
      else
        format.html { render :new }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutorials/1
  # PATCH/PUT /tutorials/1.json
  def update
    respond_to do |format|
      if @tutorial.update(tutorial_params)
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutorial }
      else
        format.html { render :edit }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    @tutorial.steps.each do |step|
      step.destroy
    end
    @tutorial.destroy
    respond_to do |format|
      format.html { redirect_to tutorials_url, notice: 'Tutorial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
    end
    def set_tutorial_and_authenticate_user
      @tutorial = Tutorial.find(params[:id])
      if @tutorial.user!=current_user && current_user.user_name!="admin"
        redirect_to root_path, notice: 'You are not allowed to do this operation.'
      end
      
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def tutorial_params
      params.require(:tutorial).permit(:title, :tutorial_level, :user_id, :topic_id, steps_attributes: [:id, :s_no, :description, :_destroy], keywords_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/_form.html.erb
<%= form_for(@tutorial) do |f| %>
  <% if @tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>
      <ul>
        <% @tutorial.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
    </div>
  <% end %>

  <div class="row">
    <!-- New Tutorial Column -->
    <div class="col-md-8">
        <h4>Title</h4>
        <%= f.text_field :title, class:'form-control' %>
        &nbsp;
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <h4>Tutorial Level</h4>
      <%= f.select :tutorial_level, [['beginner',1],['easy',2],['medium',3],['hard',4],['expert',5]], {:include_blank => false},{:class => 'form-control'}%>
      &nbsp;

      <h4>Topic</h4>
      <%= f.collection_select :topic_id, Topic.all, :id, :name, {:include_blank => false},{:class => 'form-control'} %>
      &nbsp;

      <h4>Keywords</h4>
      <%= f.fields_for :keywords do |keyword|%> 
        <%=render 'keyword_fields', :f => keyword%>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'add keywords', f, :keywords%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
        <h4>Steps</h4>
        <%=f.fields_for :steps do |step|%> 
          <%=render 'step_fields', :f => step%>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'add steps', f, :steps%>
        </div>
    </div>
  </div>
                     
  <div class="row">
    <div class="col-md-4">
      <%= f.submit  class:'btn btn-lg btn-default btn-block'%>
     </div>
  </div>
  <hr>
<% end %>

app/views/tutorials/_keyword_fields.html.erb
 <div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
	<%= link_to_remove_association "remove keyword", f%>
  </div>
   
 </div>

app/views/tutorials/_step_fields.html.erb
 <div class="nested-fields">
  <div class="field">
    <%= f.label :step_order %>
    <%= f.number_field :s_no %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
    <%= link_to_remove_association "remove step", f%><br><br><br>
 </div>

app/views/tutorials/edit.html.erb
<!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Editing Tutorial
                    <small></small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <%= render 'form' %>
        <div class="row">

                <div class="col-md-8">

                <%= link_to 'Back', @tutorial, class:'btn btn-lg btn-default btn-block', style:'width:10%', type:'submit' %>
                </div>


        </div>
        <!-- /.row -->

app/views/tutorials/index.html.erb
<div class="row">
            <div class="col-lg-12">
              <h1 class="page-header">Listing Tutorials
                    
                </h1>
            </div>
        </div>

<!-- <%= url_for :controller => 'tutorials', :action => 'myindex' %> -->
 <div class="col-md-12"> 
<div class="well">
<table style="margin-left:30px">
  <thead>
    <tr>
      <th style="padding-right:20px"><h1 class="page-header"><small> Title</small></h1></th>
      <th style="padding-right:20px"><h1 class="page-header"><small> Tutorial level</small></h1></th>
      <th style="padding-right:20px"><h1 class="page-header"><small> User</small></h1></th>
      <th style="padding-right:20px"><h1 class="page-header"><small> Topic</small></h1></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutorials.each do |tutorial| %>
      <tr>
        <td style="padding-right:20px; text-align:left"><%= link_to tutorial.title, tutorial %></td>
		
        <td style="padding-right:20px;text-align:center"><%= tutorial.tutorial_level %></td>
        <td style="padding-right:20px; text-align:center"><%= link_to tutorial.user.user_name, tutorial.user %></td>
        <td style="padding-right:20px; text-align:center"><%= link_to tutorial.topic.name, tutorial.topic %></td>
      	
        <%if current_user && current_user.user_name=='admin'%>
          <td style="padding-right:20px"><%= link_to 'Edit', edit_tutorial_path(tutorial) %></td>
          <td style="padding-right:20px"><%= link_to 'Destroy', tutorial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/tutorials/myindex.html.erb
	<%if @tutorials.count>0%>
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                 My Tutorials
                </h1>
            </div>
        </div>
        <!-- /.row -->
        

        <div class="row">

                <div class="col-md-8">
                <!-- My Tutorials Well -->
                <div class="well">
                    <h4>List of Tutorials</h4>
                    <%@tutorials.each do |tutorial|%>
                    <div class="row">
                        <div class="col-lg-12">
                            <ul class="list-unstyled">
                                <li><span><%=link_to tutorial.title, tutorial%></span><span>&nbsp;(<%=tutorial.topic.category.name%>:<%=tutorial.topic.name%>)</span><span><%= link_to ' Edit ', edit_tutorial_path(tutorial) %><%= link_to ' Destroy ', tutorial, method: :delete, data: { confirm: 'Are you sure?' } %></span>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                    <%end%>
                </div>

            </div>

            <%else%>
			<p>You haven't created any tutorials. <%=link_to 'Create here', new_tutorial_path %><p>


        </div>
        <!-- /.row -->
  <%end%>

app/views/tutorials/new.html.erb
<!-- Page Heading/Breadcrumbs -->
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">New Tutorial</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="col-md-4">
    <%= link_to 'Back', root_path, class:'btn btn-lg btn-default btn-block', type:'submit' %>
  </div>
</div>

app/views/tutorials/show.html.erb
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    <small><%= link_to 'Home', categories_path %> > <%= link_to @tutorial.topic.category.name, @tutorial.topic.category%> >  <%= link_to @tutorial.topic.name, @tutorial.topic %> > <%= @tutorial.title %></small></br> 

                    <!-- <small>Name:</small> <small><%= @tutorial.title %></small>  -->
                    <small colspan="3"></small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">


            <!-- Tutorial Details Column -->
            <div class="col-md-8">

                    <div class="well">
                       <h4>Title: <%= @tutorial.title %></h4>
                       <br/>
                    
                       <h4>Tutorial Level: <%= @tutorial.tutorial_level %></h4>
                       <br/>

                       <h4>Author: <%= @tutorial.user.user_name %> </h4>
                       <br/>

                       <h4>Keywords:
                       <%@tutorial.keywords.each do |keyword|%>
                         <%=keyword.name%>
                       <%end%>
                       </h4>
                       <br/>

                       <h4>Belongs to Topic: <%= @tutorial.topic.name %></h4>
                       <br/>

                       <h4>Steps:</h4>
                       <%@tutorial.steps.each do |step|%>
                       <p>
                         &nbsp;&nbsp;<%=step.s_no%>.&nbsp;<%=step.description%>
                       </p>
                       <%end%>
                       <br/>

                       <h4>Reviews:
                         <%if @avg_score%>
	                   (Average score: <%=sprintf('%.2f', @avg_score)%>)
	                 <%else%>
	                   (0 reviews)
	                 <%end%>
                       </h4>
                       <%@tutorial.rate_user_tutorials.each do |rate|%>
                         <p> 
                           <%=rate.score%>/5 rated by <%=rate.user.user_name%>
                         </p>
                       <%end%>
                       <br/>
                        

                       <h4>Views:</h4>                      
                      <%@tutorial.read_users.each do |user|%>
                       <p>
                        Read by <%=user.user_name%>
                      </p>
                      <%end%>
                       <br/>

                      <h4>Recommend Tutorials:</h4>                      
                      <%@relavent_tutorials.each do |tutorial|%>
                        <p>
                          <%=link_to tutorial.title, tutorial%>
                        </p>
                      <%end%>
                    </div>  

                    
                    <%if current_user && (current_user==@tutorial.user || current_user.user_name=='admin' )%>
                    <%= link_to 'Edit', edit_tutorial_path(@tutorial),class:"btn btn-lg btn-default btn-block",style:"width:25%",type:"submit",value:"Edit"%>
					<%= link_to 'Delete',@tutorial, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-lg btn-default btn-block",style:"width:25%",type:"submit",value:"Delete"%>
                      <%else %>
                    <%= link_to 'Rate', new_rate_user_tutorial_path(:tutorial_id => @tutorial.id), class:"btn btn-lg btn-default btn-block",style:"width:25%",type:"submit" %>
                    <%end%>
               
            </div>

        </div>
        <!-- /.row -->