config/routes.rb
Rails.application.routes.draw do
  resources :requests

  get 'statistics/basic'

  get 'sessions/new'

  resources :rate_user_tutorials

  resources :read_user_tutorials

  resources :keyword_tutorials

  resources :steps

  resources :categories

  resources :topics

  resources :keywords

  resources :users

  resources :tutorials
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  get    'mytutorials'  => 'tutorials#myindex'
  get    'statistics'  => 'statistics#basic'
  
  
  

  root 'categories#index'

end

app/models/request.rb
class Request < ActiveRecord::Base
  validates :user_id, presence: true
  validates :topic_id, presence: true
  belongs_to :user
  belongs_to :topic
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :set_request_and_authenticate_user, only: [:edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    if !logged_in?
      redirect_to loggin_path
    end
    @request = Request.new(request_params)
    @request.user_id = current_user.id

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end
    def set_request_and_authenticate_user
      @request = Request.find(params[:id])
      if @request.user_id != current_user.id
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:title, :topic_id, :user_id)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<br>
    <h4><%= f.label :title  %><h4>
    <%= f.text_field :title, class:'form-control' %>
  </div>
  <div class="field">
    <!-- <%= f.label :topic_id %><br> -->
    <!-- <%= f.number_field :topic_id %> -->
    <div class="dl-horizontal"><h4><%= f.label "Topic" %><h4></div>
    <div class="dl-horizontal"><%= f.collection_select :topic_id, Topic.all, :id, :name, {:include_blank => false},{:class => 'form-control'} %></div>
  </div>
  <!-- <div class="field"> -->
    <!-- <%= f.label :user_id %><br> -->
    <!-- <%= f.number_field :user_id %> -->
  <!-- </div> -->
  <div class="actions">
    <%= f.submit class:'btn btn-lg btn-default btn-block'%>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request, class:'btn btn-lg btn-default btn-block', style:'width:10%', type:'submit' %>
<%= link_to 'Back', requests_path, class:'btn btn-lg btn-default btn-block', style:'width:10%', type:'submit' %>

app/views/requests/index.html.erb
<h1>Do you need more tutorials?</h1>
<h1>Tell us more.</h1>
<hr/>

<%= link_to 'New Request', new_request_path, :class => "btn btn-lg btn-default" %>
<p>&nbsp;</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="text-left">Title</th>
      <th class="text-center">Topic</th>
      <th class="text-center">User</th>
      <th colspan="3" class="text-center">Your Action</th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr class="text-center" >
        <td class="text-left"><%= request.title %></td>
        <td><%= request.topic.name %></td>
        <td><%= request.user.user_name %></td>
        <% if current_user && current_user.id == request.user_id %>
          <td><%= link_to 'Show', request %></td>
          <td><%= link_to 'Edit', edit_request_path(request) %></td>
          <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path, class:'btn btn-lg btn-default btn-block', style:'width:10%', type:'submit' %>

app/views/requests/show.html.erb
<div class="well">
  <p>
    <strong>Title:</strong>
    <%= @request.title %>
  </p>
  
  <p>
    <strong>Topic:</strong>
    <!-- <%= @request.topic_id %> -->
    <%= Topic.find(@request.topic_id).name %>
  </p>
  
  <p>
    <strong>User:</strong>
    <!-- <%= @request.user_id %> -->
    <%= User.find(@request.user_id).user_name %>
  </p>
  
  <%= link_to 'Edit', edit_request_path(@request),class:"btn btn-lg btn-default btn-block",style:"width:25%",type:"submit"%>
	<%= link_to 'Back', requests_path, class:'btn btn-lg btn-default btn-block', style:'width:25%', type:'submit' %>
</div>