config/routes.rb
Rails.application.routes.draw do
  resources :requests

  get 'statistics/basic'

  get 'sessions/new'

  resources :rate_user_tutorials

  resources :read_user_tutorials

  resources :keyword_tutorials

  resources :steps

  resources :categories

  resources :topics

  resources :keywords

  resources :users

  resources :tutorials
  
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  get    'mytutorials'  => 'tutorials#myindex'
  get    'statistics'  => 'statistics#basic'
  
  
  

  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  #Category(id: integer, name: string, created_at: datetime, updated_at: datetime) 
    validates :name, presence: true
    has_many :topics
    has_many :tutorials, :through=>:topics
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:new, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @topics=@category.topics
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
    def check_admin
  		if !logged_in? || current_user.user_name!='admin'
        redirect_to root_path, notice: "Sorry, you don't have privilege to change category."
      end
		
  		end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <!-- Page Content -->
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <!-- New Category Details Column -->
    <div class="col-md-4">
        <h4>Title</h4>
          <%= f.text_field :name, class:'form-control' %> 
          <p>&nbsp;</p>
          <%= f.submit class:'btn btn-lg btn-default btn-block'%>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Editing Category
                    <small></small>
                </h1>
            </div>
        </div>
        <!-- /.row -->


 				<%= render 'form' %>
 				<div class="row">
                <div class="col-md-8">
                	<%= link_to 'Show', @category, class:'btn btn-lg btn-default btn-block', style:'width:10%', type:'submit' %> 
					<%= link_to 'Back', categories_path, class:'btn btn-lg btn-default btn-block', style:'width:10%', type:'submit' %>

                 </div>


        </div>
        <!-- /.row -->

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-md-12">
      <h1 class="page-header">Categories
        </h1>
    </div>
</div>

<div class="row">
  <div class="col-md-8 well">
    <!-- Categories List Well -->
      <h4>List of Categories and Topics</h4>
      <% @categories.each do |category| %>
        <p>
          <strong><%= link_to category.name, category %></strong>&nbsp;(<%=category.tutorials.count%> tutorials)
          <%if current_user && current_user.user_name=='admin'%>
            <%= link_to ' Edit ', edit_category_path(category) %>
            <%= link_to ' Destroy ', category, method: :delete, data: { confirm: 'Are you sure?' } %>
          <%end%>
          <ul>
            <% category.topics.each do |topic| %>
              <li>
                <%= link_to topic.name, topic %>&nbsp;(<%=topic.tutorials.count%> tutorials)
              </li>
            <%end%>
          </ul>
        </p>
      <%end%>
  </div>

  <div class="col-md-4">
    <br>
    <%if current_user && current_user.user_name=='admin'%>
    <%= link_to 'New Category', new_category_path, class:'btn btn-lg btn-default btn-block', type:'submit', value:'New Category' %>
    <%end%>
    
    <br>
    <%if current_user && current_user.user_name=='admin'%>
    <%= link_to 'New Topic', new_topic_path, class:'btn btn-lg btn-default btn-block', type:'submit', value:'New Topic' %>
    <%end%>
  </div>
</div>

app/views/categories/new.html.erb
<!-- Page Heading/Breadcrumbs -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">New Category</h1>
  </div>
</div>

<%= render 'form' %>

<div class="row">
  <div class="col-md-4">
    <%= link_to 'Back', categories_path, class:'btn btn-lg btn-default btn-block', type:'submit' %>
  </div>
</div>

app/views/categories/show.html.erb
<!-- Page Heading/Breadcrumbs -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
	                <small><%= link_to 'Home', categories_path %> > <%=@category.name%>
					</small></br>
            <!-- <small>Name:</small><small><%= @category.name %></small>  -->
            <small colspan="3"></small>
        </h1>
    </div>
</div>

<div class="row">
  <div class="col-md-8">
    <!-- Topics List  Well -->
    <div class="well">
      <h4>List of Topics</h4>
      <% @topics.each do |topic| %>
        <div class="row">
          <div class="col-md-12">
            <ul class="list-unstyled">
              <li>
                <%= link_to topic.name,topic %>&nbsp;(<%=topic.tutorials.count%> tutorials)
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <%if current_user && current_user.user_name=='admin'%>
        <%= link_to 'Edit', edit_category_path(@category), class:'btn btn-lg btn-default btn-block', type:'submit' %>
        <%= link_to 'Back', categories_path, class:'btn btn-lg btn-default btn-block', type:'submit' %>
      <%end%>
    </div>
  </div>

  <div class="col-md-4">
    <br/>
    <%if current_user && current_user.user_name=='admin'%>
      <%= link_to 'New Category', new_category_path, class:'btn btn-lg btn-default btn-block', type:'submit', value:'New Category' %>
    <%end%>
    <br/>
    <%if current_user && current_user.user_name=='admin'%>
      <%= link_to 'New Topic', new_topic_path, class:'btn btn-lg btn-default btn-block', type:'submit', value:'New Topic' %>
    <%end%>
  </div>
</div>